### ISSUE TITLE
Android setup

### ISSUE THREAD

**Issue by BrainBoxBrown** [hoobs-org/soma-connect#8]
When I try and use the device through goolge home, the soma service on the pi crashes. Any work arounds?

**Comment by BrainBoxBrown** [comment]
Here is the crash from `$ journalctl -f -u soma-connect`


```
Jan 29 21:09:54 berry soma-connect[511]: [[21:09:54.136]] [LOG]   ALEXA: MQTT: OnMessage: a8:27:eb:70:6b:1b/in/getShadeState: {"mac":"dc:21:13:44:63:57","correlationId":"42441328-5793-850d-df13-d09569ab02f7"}
Jan 29 21:09:55 berry soma-connect[511]: [[21:09:55.462]] [ERROR] TypeError: undefined is not a function
Jan 29 21:09:55 berry soma-connect[511]:     at AlexaManager.onGetShadeState (/snapshot/src/alexa_manager.js:0:0)
Jan 29 21:09:55 berry soma-connect[511]:     at AlexaManager.mqttOnMessage (/snapshot/src/alexa_manager.js:0:0)
Jan 29 21:09:55 berry soma-connect[511]:     at MqttClient.__dirname.mqttInitialize.mqtt_.on (/snapshot/src/alexa_manager.js:0:0)
Jan 29 21:09:55 berry soma-connect[511]:     at emitThree (events.js:135:13)
Jan 29 21:09:55 berry soma-connect[511]:     at MqttClient.emit (events.js:216:7)
Jan 29 21:09:55 berry soma-connect[511]:     at MqttClient._handlePublish (/snapshot/src/node_modules/mqtt/lib/client.js:956:12)
Jan 29 21:09:55 berry soma-connect[511]:     at MqttClient._handlePacket (/snapshot/src/node_modules/mqtt/lib/client.js:315:12)
Jan 29 21:09:55 berry soma-connect[511]:     at work (/snapshot/src/node_modules/mqtt/lib/client.js:271:12)
Jan 29 21:09:55 berry soma-connect[511]:     at Writable.MqttClient._setupStream.writable._write (/snapshot/src/node_modules/mqtt/lib/client.js:281:5)
Jan 29 21:09:55 berry soma-connect[511]:     at doWrite (/snapshot/src/node_modules/readable-stream/lib/_stream_writable.js:428:64)
Jan 29 21:09:55 berry soma-connect[511]:     at writeOrBuffer (/snapshot/src/node_modules/readable-stream/lib/_stream_writable.js:417:5)
Jan 29 21:09:55 berry soma-connect[511]:     at Writable.write (/snapshot/src/node_modules/readable-stream/lib/_stream_writable.js:334:11)
Jan 29 21:09:55 berry soma-connect[511]:     at TLSSocket.ondata (_stream_readable.js:626:20)
Jan 29 21:09:55 berry soma-connect[511]:     at emitOne (events.js:115:13)
Jan 29 21:09:55 berry soma-connect[511]:     at TLSSocket.emit (events.js:210:7)
Jan 29 21:09:55 berry soma-connect[511]:     at addChunk (_stream_readable.js:250:12)
Jan 29 21:09:55 berry soma-connect[511]:     at readableAddChunk (_stream_readable.js:237:11)
Jan 29 21:09:55 berry soma-connect[511]:     at TLSSocket.Readable.push (_stream_readable.js:195:10)
Jan 29 21:09:55 berry soma-connect[511]:     at TLSWrap.onread (net.js:586:20)
```

**Comment by mkellsy** [comment]
We only re-publish soma-connect.
You will need to open a support ticket with Soma
https://support.somasmarthome.com/
